### ISSUE TITLE
file '...' created

### ISSUE THREAD

**Issue by watdafox** [jasonrojas/node-captions#21]
Hello,

your module creates a file named `...` which is undeletable in Windows

**Comment by CorbinDallas** [comment]
Can you provide the steps/files required to reproduce the undesirable behavior?

**Comment by watdafox** [comment]
1) I have a package.json with `"node-captions": "0.4.4",` in the "dependencies".
2) `npm install`
3) module gets installed in `node_modules` directory, but it's containing a `...` file

![1](https://cloud.githubusercontent.com/assets/10504232/8765855/5d718402-2e22-11e5-9f45-573a48e5f713.png)

**Comment by watdafox** [comment]
In the meantime, if anyone sees this post and wonder how to delete the file, you can do it with node: 

```
require('fs').unlinkSync('PATH_TO_NODEMODULES\\node-captions\\...')
```

**Comment by CorbinDallas** [comment]
I can reproduce the problem, looking into the cause.

**Comment by CorbinDallas** [comment]
From a cursory look at it the bug appears to be related to NPM and not node-captions.  I'll have to spend some more time on it to say with 100% certainty, but node-captions has no file called "..." in it obviously and we have no post-install scripts that run nor do any of the dependencies, so all that's left is NPM and there are quite a few open issues with NPM and windows currently.  I can reproduce the problem in windows, windows vm and osx so I think we should leave the issue open until this is confirmed.

**Comment by watdafox** [comment]
it might be yeah, the issue happens when using `npm install` but cloning your git repo and and building the code doesn't do that. Any chance you somehow messed up with `npm publish`? ^^ Only idea that comes to mind.

**Comment by jasonrojas** [comment]
I think this was an issue with npm publish and bad file in my local directory. Can you try the latest version and see what happens?

**Comment by watdafox** [comment]
will do in a few

**Comment by watdafox** [comment]
yep, all works on 0.4.6 ;)
